### ISSUE TITLE
[coc.nvim] Error on activate extension coc-lit-html: api.configurePlugin is not a function

### ISSUE THREAD

**Issue by gitaarik** [fannheyward/coc-lit-html#95]
Hi there, nice project! However, I'm getting this error when I open a `.js` file:

    [coc.nvim] Error on activate extension coc-lit-html: api.configurePlugin is not a function

Any ideas?

**Comment by fannheyward** [comment]
Upgrade your coc.nvim please, this has been fixed already https://github.com/fannheyward/coc-deno/issues/109

**Comment by gitaarik** [comment]
Cool, thanks :+1:
